---
apiVersion: v1
kind: Service
metadata:
  name: suryaservice
  labels:
    app: suryanginx
    service: suryaservice
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
  selector:
    app: suryanginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: suryanginxdeployment
  labels:
    app: suryanginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: suryanginx
  template:
    metadata:
      labels:
        app: suryanginx
    spec:
      containers:
      - name: suryanginx
        image: suryanagababu/surya-nginx:v2.0
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        envFrom:
          - configMapRef:
              name: suryanginxdeployment
      imagePullSecrets:
      - name: suryasecrets
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: suryanginxdeployment
data:
  x: "surya"
---



